#!/usr/bin/perl

use v5.30;
use warnings;
use strict;

# Use fast_abs_path instead of realpath because the former doesn't resolve links
use Cwd qw/getcwd fast_abs_path/;
use List::Util 'min';
use File::Basename 'basename';

my ($count, $path) =
  scalar @ARGV >= 2 ? @ARGV
  : scalar @ARGV < 1 ? (1, getcwd)
  :  $ARGV[0] =~ /^\d+$/ ? ($ARGV[0], getcwd) : (1, $ARGV[0]);

opendir my $dir, $path or die "Cannot open Directory: $path";
chdir $path;

no warnings 'uninitialized';
my @files =
  sort { (stat($b))[9] <=> (stat($a))[9] }
  grep {!/^\.{1,2}$/}
  grep { basename($0) ne 'lmf' || ! -d }
  readdir $dir;
use warnings 'uninitialized';

closedir $dir;

local $, = -p STDOUT ? "\0" : "\n";
local $\ = $,;
print map { fast_abs_path $_ } @files[0..min(scalar @files, $count)-1];
